name: Notify Repo B

on:
  push:
    branches:
      - dev

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository B Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/tomasGonz67/is373hexo/dispatches \
          -d '{"event_type":"trigger-deployment"}'
